export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const FETCH_TOP_RATED_SUCCESS = "FETCH_TOP_RATED";
export const FETCH_ACTION_SUCCESS = "FETCH_ACTION_SUCCESS";
export const FETCH_COMEDY_SUCCESS = "FETCH_COMEDY_SUCCES";
export const FETCH_HORROR_SUCCESS = "FETCH_HORROR_SUCCES";
export const FETCH_ROMANTIC_SUCCESS = "FETCH_ROMANTIC_SUCCES";
export const FETCH_DOCUMENTARIES_SUCCESS = "FETCH_DOCUMENTARIES_SUCCES";

export const SEARCH_DATA_REQUEST = "SEARCH_DATA_REQUEST";
export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS";
export const SEARCH_DATA_FAILED = "SEARCH_DATA_FAILED";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const MOVIE_INFO = "MOVIE_INFO";
